import { CATEGORY_LABELS } from "../../shared/settings";
import type { ActionRecord, AnalyticsSummary, Category, ModerationAlert } from "../../shared/types";

const fmtDuration = (ms: number) => {
  const s = Math.floor(ms / 1000);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  return h ? `${h}h ${m}m` : `${m}m ${s % 60}s`;
};

const time = (t: number) => new Date(t).toISOString().slice(11, 16) + " UTC";

/** Post-LIVE report as Markdown (downloadable from the Analytics view). */
export function buildReportMarkdown(a: AnalyticsSummary, topAlerts: ModerationAlert[], actions: ActionRecord[]): string {
  const lines: string[] = [];
  const s = a.session;
  lines.push(`# NOVUS LIVE — Post-LIVE report`);
  lines.push("");
  if (s) {
    lines.push(`**Session:** ${s.title} (${s.source}) · started ${new Date(s.startedAt).toISOString()} · duration ${fmtDuration(a.durationMs)}`);
    lines.push("");
  }
  lines.push(`## Overview`);
  lines.push(`| Metric | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Total messages | ${a.totals.messages} |`);
  lines.push(`| Unique chatters | ${a.totals.uniqueChatters} |`);
  lines.push(`| Peak activity | ${a.peak ? `${a.peak.messages} msg/min at ${time(a.peak.t)}` : "—"} |`);
  lines.push(`| Alerts | ${a.totals.alerts} (${a.totals.critical} critical, ${a.totals.warnings} warning) |`);
  lines.push(`| Mute recommendations | ${a.totals.muteRecommendations} |`);
  lines.push(`| Block recommendations | ${a.totals.blockRecommendations} |`);
  lines.push(`| Report recommendations | ${a.totals.reportRecommendations} |`);
  lines.push(`| Moderation actions | ${a.totals.actions} (${a.totals.manualActions} manual in TikTok) |`);
  lines.push(`| Avg. moderation response time | ${a.avgResponseTimeMs !== null ? `${(a.avgResponseTimeMs / 1000).toFixed(1)}s` : "—"} |`);
  lines.push(`| Gifts / follows | ${a.totals.gifts} / ${a.totals.follows} |`);
  lines.push("");

  const cats = Object.entries(a.categoryCounts).sort((x, y) => (y[1] ?? 0) - (x[1] ?? 0));
  if (cats.length) {
    lines.push(`## Detected categories`);
    for (const [c, n] of cats) lines.push(`- ${CATEGORY_LABELS[c as Category]?.en ?? c}: ${n}`);
    lines.push("");
  }
  if (topAlerts.length) {
    lines.push(`## Most serious incidents`);
    for (const al of topAlerts) {
      lines.push(`- **${al.severity.toUpperCase()} ${al.riskScore}** @${al.viewer.username}: “${al.text}” — ${al.reasons.slice(0, 3).join(", ")} → ${al.recommendedAction.toUpperCase()} (${al.status})`);
    }
    lines.push("");
  }
  const real = actions.filter((x) => x.adapter !== "novus-ai");
  if (real.length) {
    lines.push(`## Moderation log`);
    for (const x of real.slice(-30)) {
      lines.push(`- ${time(x.performedAt)} ${x.action.toUpperCase()} @${x.viewer.username} — ${x.status}${x.confirmedAt ? " (confirmed)" : ""}${x.note ? ` — ${x.note}` : ""}`);
    }
    lines.push("");
  }
  if (a.topParticipants.length) {
    lines.push(`## Top participants`);
    for (const p of a.topParticipants) lines.push(`- @${p.viewer.username}: ${p.messages} messages (max risk ${p.maxRisk})`);
    lines.push("");
  }
  if (a.topQuestions.length) {
    lines.push(`## Top questions`);
    for (const q of a.topQuestions) lines.push(`- “${q.question}” ×${q.count} ${q.answered ? "(answered)" : "(unanswered)"}`);
    lines.push("");
  }
  if (a.topTopics.length) {
    lines.push(`## Top topics`);
    lines.push(a.topTopics.map((t) => `${t.topic} (${t.count})`).join(" · "));
    lines.push("");
  }
  lines.push(`_Generated by NOVUS LIVE · Part of the Novarys / Pulse Engine ecosystem._`);
  return lines.join("\n");
}
