import PDFDocument from "pdfkit";
import { CATEGORY_LABELS } from "../../shared/settings";
import { tr, word } from "../../shared/i18n";
import type { AnalyticsSummary, Category, ChatLine, HistoryEntry } from "../../shared/types";

/*
 * Post-LIVE report as a PDF: overview, audience, gifts, activity chart, participants,
 * moderation, and the full chat transcript as an appendix.
 *
 * Uses PDFKit's built-in Helvetica (WinAnsi), so characters it cannot encode (emoji,
 * most non-Latin scripts) are dropped from names and messages rather than printed as junk.
 */

type Lang = "en" | "fr";

const GOLD = "#b8894a";
const INK = "#15130f";
const MUTED = "#6b645a";
const LINE = "#ddd5c8";
const DARK = "#0b0a0c";
const RED = "#c81e32";
const ORANGE = "#d9711c";

const T = {
  en: {
    title: "LIVE report",
    status: { live: "LIVE in progress", ended: "Ended", interrupted: "Interrupted (server restart) — stats up to the last save" },
    start: "Start",
    end: "End",
    duration: "Duration",
    overview: "Overview",
    messages: "Messages",
    chatters: "Chatters",
    peakViewers: "Peak viewers",
    avgViewers: "Average viewers",
    gifts: "Gifts",
    diamonds: "Diamonds",
    donors: "Donors",
    follows: "New follows",
    joins: "Joins announced",
    alerts: "Alerts",
    actions: "Moderation actions",
    response: "Avg. response time",
    activity: "Activity per minute",
    legendMsgs: "messages / min",
    legendViewers: "viewers",
    topDonors: "Top donors",
    giftTypes: "Gifts by type",
    rank: "#",
    user: "Viewer",
    count: "Count",
    gift: "Gift",
    topChatters: "Most active chatters",
    maxRisk: "Max risk",
    questions: "Top questions",
    topics: "Trending topics",
    moderation: "Moderation",
    categories: "Detected categories",
    incidents: "Most serious incidents",
    log: "Moderation log",
    transcript: "Appendix — chat transcript",
    transcriptNote: (shown: number, total: number) => (shown < total ? `${shown} of ${total} messages (most recent).` : `${total} messages.`),
    none: "—",
    seen: (n: number) => `Individually seen viewers: ${n} (TikTok only reports viewers who chat, gift, follow, or part of the joins).`,
    generated: "Generated by NOVUS LIVE",
    page: "Page",
    critical: "critical",
    warning: "warning",
    manual: "manual in TikTok",
    confirmed: "confirmed",
  },
  fr: {
    title: "Rapport de LIVE",
    status: { live: "LIVE en cours", ended: "Terminé", interrupted: "Interrompu (redémarrage serveur) — stats jusqu'à la dernière sauvegarde" },
    start: "Début",
    end: "Fin",
    duration: "Durée",
    overview: "Vue d'ensemble",
    messages: "Messages",
    chatters: "Participants au chat",
    peakViewers: "Pic de spectateurs",
    avgViewers: "Spectateurs en moyenne",
    gifts: "Cadeaux",
    diamonds: "Diamants",
    donors: "Donateurs",
    follows: "Nouveaux abonnés",
    joins: "Arrivées annoncées",
    alerts: "Alertes",
    actions: "Actions de modération",
    response: "Temps de réaction moyen",
    activity: "Activité minute par minute",
    legendMsgs: "messages / min",
    legendViewers: "spectateurs",
    topDonors: "Meilleurs donateurs",
    giftTypes: "Cadeaux par type",
    rank: "#",
    user: "Spectateur",
    count: "Nombre",
    gift: "Cadeau",
    topChatters: "Participants les plus actifs",
    maxRisk: "Risque max",
    questions: "Questions les plus posées",
    topics: "Sujets du moment",
    moderation: "Modération",
    categories: "Catégories détectées",
    incidents: "Incidents les plus graves",
    log: "Journal de modération",
    transcript: "Annexe — transcription du chat",
    transcriptNote: (shown: number, total: number) => (shown < total ? `${shown} messages sur ${total} (les plus récents).` : `${total} messages.`),
    none: "—",
    seen: (n: number) => `Spectateurs vus individuellement : ${n} (TikTok ne signale que ceux qui écrivent, offrent, suivent, ou une partie des arrivées).`,
    generated: "Généré par NOVUS LIVE",
    page: "Page",
    critical: "critiques",
    warning: "avertissements",
    manual: "manuelles dans TikTok",
    confirmed: "confirmée",
  },
} as const;

// Helvetica in PDFKit encodes WinAnsi: keep Latin-1 plus the few extra WinAnsi glyphs.
const PRINTABLE = /[^\x20-\x7e\u00a0-\u00ff\u0152\u0153\u0160\u0161\u0178\u017d\u017e\u2013\u2014\u2018\u2019\u201a\u201c\u201d\u201e\u2020\u2021\u2022\u2026\u2030\u2039\u203a\u20ac\u2122]/g;
// French number/date formatting uses narrow no-break spaces, which WinAnsi lacks.
const spaces = (s: string) => s.replace(/[\u202f\u2009\u2007\u00a0]/g, " ");
export const pdfText = (s: string) => spaces(s).replace(/[\r\n\t]+/g, " ").replace(PRINTABLE, "").replace(/\s{2,}/g, " ").trim();

const MAX_TRANSCRIPT = 15_000;

export interface PdfInput {
  entry: HistoryEntry;
  analytics: AnalyticsSummary;
  chat: ChatLine[];
  lang: Lang;
  timeZone: string;
  logo?: Buffer;
}

export function buildReportPdf(input: PdfInput): Promise<Buffer> {
  const { entry, analytics: a, chat, lang, timeZone, logo } = input;
  const t = T[lang];
  const locale = lang === "fr" ? "fr-FR" : "en-GB";
  const dateFmt = new Intl.DateTimeFormat(locale, { timeZone, dateStyle: "full", timeStyle: "short" });
  const timeFmt = new Intl.DateTimeFormat(locale, { timeZone, hour: "2-digit", minute: "2-digit" });
  const clockFmt = new Intl.DateTimeFormat(locale, { timeZone, hour: "2-digit", minute: "2-digit", second: "2-digit" });
  const fmtDate = { format: (v: number) => spaces(dateFmt.format(v)) };
  const fmtTime = { format: (v: number) => spaces(timeFmt.format(v)) };
  const fmtClock = { format: (v: number) => spaces(clockFmt.format(v)) };
  const n = (v: number) => spaces(v.toLocaleString(locale));
  const dur = (ms: number) => {
    const s = Math.max(0, Math.floor(ms / 1000));
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    return h ? `${h} h ${String(m).padStart(2, "0")}` : `${m} min ${String(s % 60).padStart(2, "0")} s`;
  };

  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 48, bottom: 56, left: 44, right: 44 },
    bufferPages: true,
    info: { Title: `NOVUS LIVE — ${pdfText(tr(entry.title, lang))}`, Author: "NOVUS LIVE", Subject: t.title },
  });
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const left = doc.page.margins.left;
  const width = doc.page.width - left - doc.page.margins.right;
  const bottom = () => doc.page.height - doc.page.margins.bottom;
  const ensure = (h: number) => {
    if (doc.y + h > bottom()) doc.addPage();
  };
  const heading = (text: string) => {
    ensure(60);
    doc.moveDown(0.8);
    doc.font("Helvetica-Bold").fontSize(13).fillColor(INK).text(text.toUpperCase(), left, doc.y, { characterSpacing: 1.2 });
    const y = doc.y + 3;
    doc.moveTo(left, y).lineTo(left + 36, y).lineWidth(2).strokeColor(GOLD).stroke();
    doc.moveDown(0.7);
  };
  const para = (text: string, opts: { color?: string; size?: number } = {}) => {
    doc.font("Helvetica").fontSize(opts.size ?? 9.5).fillColor(opts.color ?? MUTED).text(text, left, doc.y, { width });
  };

  /** Simple table with a header row and automatic page breaks. */
  const table = (cols: { label: string; w: number; align?: "left" | "right" }[], rows: string[][]) => {
    const rowH = 17;
    const drawHeader = () => {
      const y = doc.y;
      let x = left;
      doc.font("Helvetica-Bold").fontSize(8.5).fillColor(MUTED);
      for (const c of cols) {
        doc.text(c.label.toUpperCase(), x + 4, y + 4, { width: c.w * width - 8, align: c.align ?? "left", lineBreak: false });
        x += c.w * width;
      }
      doc.moveTo(left, y + rowH).lineTo(left + width, y + rowH).lineWidth(0.6).strokeColor(LINE).stroke();
      doc.y = y + rowH;
    };
    ensure(rowH * 3);
    drawHeader();
    for (const r of rows) {
      if (doc.y + rowH > bottom()) {
        doc.addPage();
        drawHeader();
      }
      const y = doc.y;
      let x = left;
      doc.font("Helvetica").fontSize(9).fillColor(INK);
      r.forEach((cell, i) => {
        const c = cols[i];
        doc.text(cell, x + 4, y + 4, { width: c.w * width - 8, align: c.align ?? "left", lineBreak: false, ellipsis: true });
        x += c.w * width;
      });
      doc.moveTo(left, y + rowH).lineTo(left + width, y + rowH).lineWidth(0.3).strokeColor(LINE).stroke();
      doc.y = y + rowH;
    }
    doc.x = left;
    doc.moveDown(0.4);
  };

  // ---------------------------------------------------------------- header band
  doc.rect(0, 0, doc.page.width, 118).fill(DARK);
  let textX = left;
  if (logo) {
    try {
      doc.image(logo, left, 22, { width: 74, height: 74 });
      textX = left + 90;
    } catch {
      /* unreadable logo: header text only */
    }
  }
  doc.font("Helvetica-Bold").fontSize(24).fillColor("#e0b877").text("NOVUS", textX, 30, { characterSpacing: 5, lineBreak: false });
  doc.font("Helvetica").fontSize(12).fillColor("#e8dcc6").text("LIVE", textX + 132, 40, { characterSpacing: 6, lineBreak: false });
  doc.font("Helvetica").fontSize(11).fillColor("#b2aaa0").text(t.title, textX, 64, { lineBreak: false });
  doc.font("Helvetica-Bold").fontSize(13).fillColor("#f1ece4").text(pdfText(tr(entry.title, lang)), textX, 81, { width: width - (textX - left), lineBreak: false, ellipsis: true });

  doc.y = 136;
  doc.x = left;
  const statusColor = entry.status === "live" ? RED : entry.status === "interrupted" ? ORANGE : GOLD;
  doc.font("Helvetica-Bold").fontSize(9).fillColor(statusColor).text(t.status[entry.status].toUpperCase(), left, doc.y, { characterSpacing: 1 });
  doc.moveDown(0.3);
  const endTxt = entry.endedAt ? fmtDate.format(entry.endedAt) : t.none;
  para(`${t.start} : ${fmtDate.format(entry.startedAt)}    ·    ${t.end} : ${endTxt}    ·    ${t.duration} : ${dur(a.durationMs || entry.durationMs)}`, { color: INK });

  // ---------------------------------------------------------------- KPI grid
  heading(t.overview);
  const kpis: [string, string][] = [
    [t.messages, n(a.totals.messages)],
    [t.chatters, n(a.totals.uniqueChatters)],
    [t.peakViewers, a.audience ? n(a.audience.peakViewers) : t.none],
    [t.avgViewers, a.audience?.avgViewers != null ? n(a.audience.avgViewers) : t.none],
    [t.gifts, n(a.gifts?.total ?? a.totals.gifts)],
    [t.diamonds, a.gifts ? n(a.gifts.diamonds) : t.none],
    [t.donors, a.gifts ? n(a.gifts.senders) : t.none],
    [t.follows, n(a.audience?.follows ?? a.totals.follows)],
    [t.joins, a.audience ? n(a.audience.joins) : t.none],
    [t.alerts, `${n(a.totals.alerts)}  (${a.totals.critical} ${t.critical})`],
    [t.actions, `${n(a.totals.actions)}`],
    [t.response, a.avgResponseTimeMs !== null ? `${(a.avgResponseTimeMs / 1000).toFixed(1)} s` : t.none],
  ];
  const colsN = 3;
  const boxW = (width - (colsN - 1) * 8) / colsN;
  const boxH = 46;
  const gridTop = doc.y;
  kpis.forEach(([label, value], i) => {
    const x = left + (i % colsN) * (boxW + 8);
    const y = gridTop + Math.floor(i / colsN) * (boxH + 8);
    doc.roundedRect(x, y, boxW, boxH, 6).lineWidth(0.7).strokeColor(LINE).stroke();
    doc.font("Helvetica-Bold").fontSize(15).fillColor(INK).text(value, x + 10, y + 8, { width: boxW - 20, lineBreak: false, ellipsis: true });
    doc.font("Helvetica").fontSize(8).fillColor(MUTED).text(label.toUpperCase(), x + 10, y + 29, { width: boxW - 20, lineBreak: false, characterSpacing: 0.5 });
  });
  doc.y = gridTop + Math.ceil(kpis.length / colsN) * (boxH + 8);
  doc.x = left;
  if (a.audience) para(t.seen(a.audience.seenViewers), { size: 8.5 });

  // ---------------------------------------------------------------- activity chart
  const buckets = a.buckets ?? [];
  if (buckets.length > 1) {
    heading(t.activity);
    ensure(170);
    const chartTop = doc.y + 4;
    const chartH = 120;
    const maxMsgs = Math.max(1, ...buckets.map((b) => b.messages));
    const maxViewers = Math.max(1, ...buckets.map((b) => b.viewers ?? 0));
    const step = width / buckets.length;
    doc.moveTo(left, chartTop + chartH).lineTo(left + width, chartTop + chartH).lineWidth(0.6).strokeColor(LINE).stroke();
    buckets.forEach((b, i) => {
      const h = (b.messages / maxMsgs) * chartH;
      if (h > 0) doc.rect(left + i * step + step * 0.12, chartTop + chartH - h, Math.max(0.6, step * 0.76), h).fill(GOLD);
    });
    const pts = buckets.map((b, i) => [left + i * step + step / 2, chartTop + chartH - ((b.viewers ?? 0) / maxViewers) * chartH] as const).filter((_, i) => (buckets[i].viewers ?? 0) > 0);
    if (pts.length > 1) {
      doc.moveTo(pts[0][0], pts[0][1]);
      for (const [x, y] of pts.slice(1)) doc.lineTo(x, y);
      doc.lineWidth(1.4).strokeColor(INK).stroke();
    }
    doc.font("Helvetica").fontSize(7.5).fillColor(MUTED);
    doc.text(fmtTime.format(buckets[0].t), left, chartTop + chartH + 4, { lineBreak: false });
    doc.text(fmtTime.format(buckets[buckets.length - 1].t), left + width - 60, chartTop + chartH + 4, { width: 60, align: "right", lineBreak: false });
    doc.text(`max ${maxMsgs} ${t.legendMsgs}`, left, chartTop - 10, { lineBreak: false });
    if (pts.length > 1) doc.text(`max ${n(maxViewers)} ${t.legendViewers}`, left + width - 160, chartTop - 10, { width: 160, align: "right", lineBreak: false });
    doc.y = chartTop + chartH + 18;
    doc.x = left;
    doc.rect(left, doc.y + 2, 8, 8).fill(GOLD);
    doc.font("Helvetica").fontSize(8).fillColor(MUTED).text(t.legendMsgs, left + 12, doc.y + 2, { lineBreak: false });
    if (pts.length > 1) {
      doc.moveTo(left + 110, doc.y + 6).lineTo(left + 124, doc.y + 6).lineWidth(1.4).strokeColor(INK).stroke();
      doc.text(t.legendViewers, left + 128, doc.y + 2, { lineBreak: false });
    }
    doc.y += 16;
    doc.x = left;
  }

  // ---------------------------------------------------------------- gifts
  if (a.gifts && a.gifts.total > 0) {
    heading(t.gifts);
    if (a.gifts.top.length) {
      doc.font("Helvetica-Bold").fontSize(10).fillColor(INK).text(t.topDonors);
      doc.moveDown(0.3);
      table(
        [
          { label: t.rank, w: 0.08 },
          { label: t.user, w: 0.52 },
          { label: t.gifts, w: 0.2, align: "right" },
          { label: t.diamonds, w: 0.2, align: "right" },
        ],
        a.gifts.top.map((g, i) => [String(i + 1), `@${pdfText(g.viewer.username)}`, n(g.gifts), n(g.diamonds)]),
      );
    }
    if (a.gifts.byName.length) {
      doc.font("Helvetica-Bold").fontSize(10).fillColor(INK).text(t.giftTypes, left);
      doc.moveDown(0.3);
      table(
        [
          { label: t.gift, w: 0.6 },
          { label: t.count, w: 0.2, align: "right" },
          { label: t.diamonds, w: 0.2, align: "right" },
        ],
        a.gifts.byName.map((g) => [pdfText(g.name) || "?", n(g.count), n(g.diamonds)]),
      );
    }
  }

  // ---------------------------------------------------------------- participants
  if (a.topParticipants.length) {
    heading(t.topChatters);
    table(
      [
        { label: t.rank, w: 0.08 },
        { label: t.user, w: 0.56 },
        { label: t.messages, w: 0.18, align: "right" },
        { label: t.maxRisk, w: 0.18, align: "right" },
      ],
      a.topParticipants.map((p, i) => [String(i + 1), `@${pdfText(p.viewer.username)}`, n(p.messages), String(p.maxRisk)]),
    );
  }

  if (a.topQuestions.length || a.topTopics.length) {
    heading(t.questions);
    if (a.topQuestions.length) {
      for (const q of a.topQuestions) {
        ensure(16);
        para(`•  ${pdfText(q.question)}  ×${q.count}`, { color: INK });
      }
    } else para(t.none);
    if (a.topTopics.length) {
      doc.moveDown(0.5);
      doc.font("Helvetica-Bold").fontSize(10).fillColor(INK).text(t.topics, left);
      para(a.topTopics.map((tp) => `${pdfText(tr(tp.topic, lang))} (${tp.count})`).join("   ·   "), { color: INK });
    }
  }

  // ---------------------------------------------------------------- moderation
  heading(t.moderation);
  para(
    `${t.alerts} : ${n(a.totals.alerts)} — ${a.totals.critical} ${t.critical}, ${a.totals.warnings} ${t.warning}.   ${t.actions} : ${n(a.totals.actions)} (${a.totals.manualActions} ${t.manual}).`,
    { color: INK },
  );
  const cats = (Object.entries(a.categoryCounts) as [Category, number][]).filter(([, v]) => v > 0).sort((x, y) => y[1] - x[1]);
  if (cats.length) {
    doc.moveDown(0.5);
    doc.font("Helvetica-Bold").fontSize(10).fillColor(INK).text(t.categories, left);
    para(cats.map(([c, v]) => `${pdfText(CATEGORY_LABELS[c]?.[lang] ?? c)} (${v})`).join("   ·   "), { color: INK });
  }
  if (a.incidents?.length) {
    doc.moveDown(0.5);
    doc.font("Helvetica-Bold").fontSize(10).fillColor(INK).text(t.incidents, left);
    doc.moveDown(0.2);
    for (const inc of a.incidents) {
      ensure(30);
      const color = inc.severity === "critical" ? RED : inc.severity === "warning" ? ORANGE : MUTED;
      doc.font("Helvetica-Bold").fontSize(8.5).fillColor(color).text(`${word(inc.severity, lang).toUpperCase()} ${inc.riskScore}`, left, doc.y, { continued: true });
      doc.fillColor(INK).text(`   ${fmtTime.format(inc.t)}  @${pdfText(inc.username)}  »  ${word(inc.recommendedAction, lang).toUpperCase()} (${word(inc.status, lang)})`);
      doc.font("Helvetica").fontSize(8.5).fillColor(MUTED).text(`“${pdfText(inc.text)}” — ${pdfText(inc.reasons.map((r) => tr(r, lang)).join(", "))}`, left + 10, doc.y, { width: width - 10 });
      doc.moveDown(0.3);
      doc.x = left;
    }
  }
  if (a.moderationLog?.length) {
    doc.moveDown(0.3);
    doc.font("Helvetica-Bold").fontSize(10).fillColor(INK).text(t.log, left);
    doc.moveDown(0.2);
    for (const l of a.moderationLog) {
      ensure(14);
      para(`${fmtTime.format(l.t)}   ${word(l.action, lang).toUpperCase()}   @${pdfText(l.username)}   ${word(l.status, lang)}${l.confirmed ? ` (${t.confirmed})` : ""}`, { color: INK, size: 8.5 });
    }
  }

  // ---------------------------------------------------------------- transcript
  if (chat.length) {
    doc.addPage();
    heading(t.transcript);
    const shown = chat.slice(-MAX_TRANSCRIPT);
    para(t.transcriptNote(shown.length, chat.length), { size: 8.5 });
    doc.moveDown(0.4);
    for (const line of shown) {
      if (doc.y + 11 > bottom()) doc.addPage();
      const flagged = line.severity === "critical" || line.severity === "warning";
      const text = pdfText(line.text) || "(emoji)";
      doc.font("Helvetica").fontSize(7.5).fillColor(MUTED).text(`${fmtClock.format(line.t)}  `, left, doc.y, { continued: true });
      doc.font("Helvetica-Bold").fillColor(flagged ? (line.severity === "critical" ? RED : ORANGE) : INK).text(`@${pdfText(line.username)}: `, { continued: true });
      doc.font("Helvetica").fillColor(INK).text(text, { width });
    }
  }

  // ---------------------------------------------------------------- footers
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    // Writing inside the bottom margin would make PDFKit start a new page.
    doc.page.margins.bottom = 0;
    const y = doc.page.height - 36;
    doc.font("Helvetica").fontSize(7.5).fillColor(MUTED);
    doc.text(`${t.generated} · ${pdfText(tr(entry.title, lang))}`, left, y, { width: width - 80, lineBreak: false, ellipsis: true });
    doc.text(`${t.page} ${i + 1}/${range.count}`, left + width - 80, y, { width: 80, align: "right", lineBreak: false });
  }
  doc.end();
  return done;
}
